name: Docker Build and Push

on:
  push:
    branches:
      - main  # Execute o workflow apenas quando houver um push na branch `main`
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuração do Docker para construção da imagem
    - name: Build Docker Image
      run: docker build -t fast-cli .

    # (Opcional) Testar a imagem criada
    - name: Run Tests
      run: docker run --rm fast-cli fast --version

    # (Opcional) Publicar no Docker Hub ou GitHub Container Registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Configure no repositório
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker tag fast-cli <DOCKER_HUB_USERNAME>/fast-cli:latest && \
           docker push <DOCKER_HUB_USERNAME>/fast-cli:latest
